--table storing weather stations
CREATE TABLE STATION (
    STATION_ID VARCHAR2(50) PRIMARY KEY,
    NAME VARCHAR2(100),
    STATE VARCHAR2(10)
);

--lookup table for weather variables
CREATE TABLE WEATHER_VARIABLE (
    VAR_CODE VARCHAR2(10) PRIMARY KEY,
    VAR_NAME VARCHAR2(50)
);

--links station and varaibles over time
CREATE TABLE OBSERVATION (
    OBS_ID NUMBER PRIMARY KEY,
    STATION_ID VARCHAR2(50),
    OBS_DATE DATE,
    VAR_CODE VARCHAR2(10),
    VALUE NUMBER,
    CONSTRAINT fk_st FOREIGN KEY (STATION_ID) REFERENCES STATION(STATION_ID),
    CONSTRAINT fk_vc FOREIGN KEY (VAR_CODE) REFERENCES WEATHER_VARIABLE(VAR_CODE)
);
